-- ~/.config/hypr/hyprland.lua
-- Hyprland configuration — Gruvbox Material Dark
-- Generated from hyprlang settings block; verify dispatcher names against
-- /usr/share/hypr/stubs/ if anything behaves unexpectedly.

-- Monitor/workspace config is per-host; generated by Nix into monitors.lua
require("monitors")
-- Host-specific environment variables (NVIDIA etc.) generated by Nix into env.lua
require("env")

--------------------
---- AUTOSTART -----
--------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland DISPLAY")
    hl.exec_cmd("GSK_RENDERER=gl swayosd-server")
    hl.exec_cmd("awww-daemon")
    -- Per-host wallpaper command(s), generated by Nix into wallpaper.lua
    -- (portrait/rotated outputs are fitted instead of crop-zoomed).
    require("wallpaper")
    -- swaync replaced by Quickshell's NotificationServer (Shell.qml)
    hl.exec_cmd("playerctld")
    hl.exec_cmd("/run/current-system/sw/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("sleep 1 && nm-applet --indicator")
    hl.exec_cmd("sleep 1.5 && syncthingtray")
    hl.exec_cmd("gammastep")
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml")
end)

--------------------
---- SETTINGS ------
--------------------

hl.config({
    cursor = {
        no_hardware_cursors = true,
        -- Keep the cursor where it is on workspace switches — hl.dsp.focus
        -- otherwise warps it to the newly focused window.
        no_warps = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    input = {
        kb_layout        = "us",
        follow_mouse     = 1,
        sensitivity      = 0,
        accel_profile    = "flat",
        touchpad = {
            natural_scroll       = true,
            disable_while_typing = true,
            tap_to_click         = true,
        },
    },

    general = {
        gaps_in         = 5,
        gaps_out        = 10,
        border_size     = 2,
        layout          = "dwindle",
        allow_tearing   = true,
        col = {
            active_border   = { colors = { "rgba(7daea3ee)", "rgba(d3869bee)" }, angle = 45 },
            inactive_border = "rgba(3c3836aa)",
        },
    },

    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size    = 3,
            passes  = 1,
        },
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    gestures = {
        workspace_swipe_distance = 300,
    },

    misc = {
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
        vrr                      = 2,
        -- If hyprlock dies, allow a fresh instance to re-take the session lock
        -- instead of dropping to Hyprland's "lockscreen app died" failsafe.
        allow_session_lock_restore = true,
    },
})

-- Animations
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",    enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7,  bezier = "default",   style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle",enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = 7,  bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6,  bezier = "default" })

---------------------
---- LAYER RULES ----
---------------------

hl.layer_rule({ match = { namespace = "waybar" },                 blur = true,  ignore_alpha = 0.0 })
hl.layer_rule({ match = { namespace = "quickshell" },             blur = true,  ignore_alpha = 0.0 })

---------------------
---- WINDOW RULES ---
---------------------

-- Gaming — allow tearing
hl.window_rule({ match = { class = "steam_app_" },                  immediate = true })
hl.window_rule({ match = { class = "Minecraft" },                   immediate = true })

-- Launchers
hl.window_rule({ match = { class = "steam",   title = "Steam Big Picture Mode" }, fullscreen = true })
hl.window_rule({ match = { class = "lutris" }, workspace = "10 silent" })
hl.window_rule({ match = { class = "steam"  }, workspace = "10 silent" })
-- Steam dropdown menus are empty-title XWayland popups; without this they
-- steal focus and land on the wrong monitor.
hl.window_rule({ match = { class = "steam", title = "^$" }, no_focus = true })

-- Float
hl.window_rule({ match = { class = "pavucontrol" },        float = true })
hl.window_rule({ match = { class = "nm-connection-editor" }, float = true })
hl.window_rule({ match = { class = "blueman-manager" },    float = true })
hl.window_rule({ match = { title = "Picture-in-Picture" }, float = true })

-- Opacity
hl.window_rule({ match = { class = "kitty" },        opacity = "0.90 override 0.90 override" })
hl.window_rule({ match = { class = "firefox" },      opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "chromium" },     opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "google-chrome" },opacity = "1.0 override 1.0 override" })

-- Workspace assignments
hl.window_rule({ match = { class = "firefox" }, workspace = "1" })
hl.window_rule({ match = { class = "Code"    }, workspace = "2" })
hl.window_rule({ match = { class = "kitty"   }, workspace = "3" })
hl.window_rule({ match = { class = "discord" }, workspace = "4" })

--------------------
---- KEYBINDS ------
--------------------

local mainMod = "SUPER"

-- Apps
hl.bind(mainMod .. " + Return",     hl.dsp.exec_cmd("kitty"),                         { description = "Apps | Terminal" })
hl.bind(mainMod .. " + E",          hl.dsp.exec_cmd("thunar"),                        { description = "Apps | Files" })
hl.bind(mainMod .. " + B",          hl.dsp.exec_cmd("zen-beta"),                      { description = "Apps | Browser" })
hl.bind(mainMod .. " + D",          hl.dsp.exec_cmd("fuzzel"),                        { description = "Apps | Launcher" })

-- Window management
hl.bind(mainMod .. " + Q",         hl.dsp.window.kill(),                                              { description = "Window | Close" })
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit(),                                                     { description = "Window | Exit Hyprland" })
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen(),                                        { description = "Window | Fullscreen" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen_state({ client = 0, internal = 3 }),      { description = "Window | Fullscreen (fake)" })
hl.bind(mainMod .. " + Space",     hl.dsp.window.float({ action = "toggle" }),                        { description = "Window | Toggle float" })
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo(),                                            { description = "Window | Pseudo tile" })
hl.bind(mainMod .. " + J",         hl.dsp.layout("togglesplit"),                                      { description = "Window | Toggle split" })

-- Focus
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { description = "Focus | Left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "Focus | Right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { description = "Focus | Up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { description = "Focus | Down" })

-- Move window
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }),  { description = "Move | Left" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }), { description = "Move | Right" })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }),    { description = "Move | Up" })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }),  { description = "Move | Down" })

-- Resize window
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -50, y = 0 }),   { description = "Resize | Left" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 50,  y = 0 }),   { description = "Resize | Right" })
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0,   y = -50 }), { description = "Resize | Up" })
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0,   y = 50 }),  { description = "Resize | Down" })

-- Workspaces 1–10
for i = 1, 10 do
    local key = tostring(i % 10)  -- 10 maps to "0"
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }),       { description = "Workspaces | Switch to " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), { description = "Workspaces | Move to " .. i })
end

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Workspaces | Next" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Workspaces | Prev" })

-- Scratchpad
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"),             { description = "Workspaces | Toggle scratchpad" })
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }),  { description = "Workspaces | Move to scratchpad" })

-- System
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("hyprlock"),                                                          { description = "System | Lock" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("systemctl suspend"),                                                 { description = "System | Suspend" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("wlogout -p layer-shell"),                                            { description = "System | Logout menu" })
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle notifications"),         { description = "System | Notifications" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle clipboard"),        { description = "System | Clipboard history" })

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle screenshot"), { description = "Screenshots | Open picker" })

-- Volume
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"),        { locked = true, description = "Media | Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"),        { locked = true, description = "Media | Volume down" })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"),  { locked = true, description = "Media | Mute" })

-- Brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set +10%"), { locked = true, description = "Media | Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"), { locked = true, description = "Media | Brightness down" })

-- Media
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Media | Play/pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),        { locked = true, description = "Media | Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),    { locked = true, description = "Media | Prev track" })

-- Gaming toggle
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/gaming-toggle.sh"), { description = "Gaming | Toggle gaming mode" })

-- Mouse binds
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
