-- ~/.config/hypr/hyprland.lua
-- Hyprland configuration — Gruvbox Material Dark
-- Generated from hyprlang settings block; verify dispatcher names against
-- /usr/share/hypr/stubs/ if anything behaves unexpectedly.

-- Monitor/workspace config is per-host; generated by Nix into monitors.lua.
-- Returns { primary = "<connector>" } ("" when the host has no pinned primary).
local mon = require("monitors")
-- Host-specific environment variables (NVIDIA etc.) and app choices
-- (terminal/browser), generated by Nix into env.lua
local apps = require("env")

--------------------
---- AUTOSTART -----
--------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland DISPLAY")
    hl.exec_cmd("awww-daemon")
    -- Per-host wallpaper command(s), generated by Nix into wallpaper.lua
    -- (portrait/rotated outputs are fitted instead of crop-zoomed).
    require("wallpaper")
    -- swaync replaced by Quickshell's NotificationServer (Shell.qml)
    hl.exec_cmd("playerctld")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    -- nm-applet + syncthingtray + the polkit agent are systemd user services
    -- (modules/home/wm/hyprland.nix); gammastep is one too (HM
    -- services.gammastep) — exec'ing them here starts duplicates.
    hl.exec_cmd("quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml")
end)

--------------------
---- SETTINGS ------
--------------------

hl.config({
    cursor = {
        no_hardware_cursors = true,
        -- Spawn the cursor on the primary monitor at startup ("" = Hyprland default)
        default_monitor = mon.primary,
        -- Keep the cursor where it is on workspace switches — hl.dsp.focus
        -- otherwise warps it to the newly focused window.
        no_warps = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    input = {
        kb_layout        = "us",
        follow_mouse     = 1,
        sensitivity      = 0,
        accel_profile    = "flat",
        touchpad = {
            natural_scroll       = true,
            disable_while_typing = true,
            tap_to_click         = true,
        },
    },

    general = {
        gaps_in         = 5,
        gaps_out        = 10,
        border_size     = 2,
        layout          = "dwindle",
        allow_tearing   = true,
        col = {
            active_border   = "rgba(@blue-hex@ee)",
            inactive_border = "rgba(@bg1-hex@aa)",
        },
    },

    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size    = 3,
            passes  = 1,
        },
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    gestures = {
        workspace_swipe_distance = 300,
    },

    misc = {
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
        vrr                      = 2,
        -- If hyprlock dies, allow a fresh instance to re-take the session lock
        -- instead of dropping to Hyprland's "lockscreen app died" failsafe.
        allow_session_lock_restore = true,
    },
})

-- Animations
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",    enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7,  bezier = "default",   style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle",enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = 7,  bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6,  bezier = "default" })

---------------------
---- LAYER RULES ----
---------------------

hl.layer_rule({ match = { namespace = "waybar" },                 blur = true,  ignore_alpha = 0.0 })
hl.layer_rule({ match = { namespace = "quickshell" },             blur = true,  ignore_alpha = 0.0 })

---------------------
---- WINDOW RULES ---
---------------------

-- Gaming — allow tearing
hl.window_rule({ match = { class = "steam_app_" },                  immediate = true })
hl.window_rule({ match = { class = "Minecraft" },                   immediate = true })
-- gaming-toggle.sh runs `gamescope -- steam -bigpicture`; the window class is
-- "gamescope", not "steam", so the Big Picture rule below never matches it.
-- Without fullscreen it stays a tiled window that Hyprland composites every
-- frame at vsync (major input lag). fullscreen + immediate lets Hyprland
-- direct-scanout the gamescope buffer straight to the display, near-native.
hl.window_rule({ match = { class = "gamescope" },                   fullscreen = true })
hl.window_rule({ match = { class = "gamescope" },                   immediate = true })

-- Launchers
-- Big Picture launched natively by gaming-toggle.sh: fullscreen + immediate so
-- Hyprland direct-scanouts it (no compositor vsync latency).
hl.window_rule({ match = { class = "steam",   title = "Steam Big Picture Mode" }, fullscreen = true })
hl.window_rule({ match = { class = "steam",   title = "Steam Big Picture Mode" }, immediate = true })
-- Steam dropdown menus are empty-title XWayland popups; without this they
-- steal focus and land on the wrong monitor.
hl.window_rule({ match = { class = "steam", title = "^$" }, no_focus = true })

-- Float
hl.window_rule({ match = { class = "pavucontrol" },        float = true })
hl.window_rule({ match = { class = "nm-connection-editor" }, float = true })
hl.window_rule({ match = { class = "blueman-manager" },    float = true })
hl.window_rule({ match = { title = "Picture-in-Picture" }, float = true })

-- Scratchpad — windows on a special workspace float centred with an orange
-- border so they read as scratchpad windows, not tiles. The static fields
-- (float/size/center) only apply to windows that open on the special; the
-- Super+Shift+S bind replicates them for windows moved there. Also used by
-- the per-app scratchpads defined with their binds below.
local function scratchpadRule(name)
    hl.window_rule({
        name  = "scratchpad-style-" .. name,
        -- The workspace matcher needs the "name:" prefix for named specials —
        -- a bare "special:X" parses as an id selector and matches nothing.
        match = { workspace = "name:special:" .. name },

        float        = true,
        size         = "65% 65%",
        center       = true,
        border_color = "rgba(@orange-hex@ee)",
    })
end
scratchpadRule("magic")

-- Opacity
hl.window_rule({ match = { class = "kitty" },        opacity = "0.90 override 0.90 override" })
hl.window_rule({ match = { class = "cava" },         opacity = "0.90 override 0.90 override" })
hl.window_rule({ match = { class = "firefox" },      opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "chromium" },     opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "google-chrome" },opacity = "1.0 override 1.0 override" })


--------------------
---- KEYBINDS ------
--------------------

local mainMod = "SUPER"

-- Apps
hl.bind(mainMod .. " + Return",     hl.dsp.exec_cmd(apps.terminal),                   { description = "Apps | Terminal" })
hl.bind(mainMod .. " + E",          hl.dsp.exec_cmd("thunar"),                        { description = "Apps | Files" })
hl.bind(mainMod .. " + B",          hl.dsp.exec_cmd(apps.browser),                    { description = "Apps | Browser" })
hl.bind(mainMod .. " + D",          hl.dsp.exec_cmd("fuzzel"),                        { description = "Apps | Launcher" })
-- cava audio visualiser — opens on workspace 4 (spare/secondary monitor) without stealing focus
hl.bind(mainMod .. " + SHIFT + C",  hl.dsp.exec_cmd("[workspace 4 silent] kitty --class cava -e cava"), { description = "Apps | Cava visualiser" })

-- Window management
hl.bind(mainMod .. " + Q",         hl.dsp.window.kill(),                                              { description = "Window | Close" })
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exit(),                                                     { description = "Window | Exit Hyprland" })
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen(),                                        { description = "Window | Fullscreen" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen_state({ client = 0, internal = 3 }),      { description = "Window | Fullscreen (fake)" })
hl.bind(mainMod .. " + Space",     hl.dsp.window.float({ action = "toggle" }),                        { description = "Window | Toggle float" })
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo(),                                            { description = "Window | Pseudo tile" })
hl.bind(mainMod .. " + J",         hl.dsp.layout("togglesplit"),                                      { description = "Window | Toggle split" })

-- Focus
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { description = "Focus | Left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { description = "Focus | Right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { description = "Focus | Up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { description = "Focus | Down" })

-- Move window
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }),  { description = "Move | Left" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }), { description = "Move | Right" })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }),    { description = "Move | Up" })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }),  { description = "Move | Down" })

-- Resize window
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -50, y = 0 }),   { description = "Resize | Left" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 50,  y = 0 }),   { description = "Resize | Right" })
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0,   y = -50 }), { description = "Resize | Up" })
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0,   y = 50 }),  { description = "Resize | Down" })

-- Workspaces 1–10
for i = 1, 10 do
    local key = tostring(i % 10)  -- 10 maps to "0"
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }),       { description = "Workspaces | Switch to " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }), { description = "Workspaces | Move to " .. i })
end

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Workspaces | Next" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Workspaces | Prev" })

-- Scratchpad
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"),             { description = "Workspaces | Toggle scratchpad" })
-- Toggle-move: windows already in a scratchpad go back to the monitor's
-- workspace instead of piling up (the emptied special auto-closes — don't
-- toggle it here, that reopens it). Stashed windows are floated/sized by
-- hand: the scratchpad-style rule's static fields only apply to windows
-- that *open* on the special, not ones moved there. Windows the stash
-- floated are remembered and re-tiled on return; windows that were already
-- floating keep floating.
local scratchpadFloated = {}
hl.bind(mainMod .. " + SHIFT + S", function()
    local win = hl.get_active_window()
    if not win or not win.workspace then return end
    if win.workspace.special then
        local mon = hl.get_active_monitor()
        local target = mon and mon.active_workspace
        if not target then return end
        hl.dispatch(hl.dsp.window.move({ workspace = target.id }))
        if scratchpadFloated[win.address] then
            scratchpadFloated[win.address] = nil
            hl.dispatch(hl.dsp.window.float({ action = "disable" }))
        end
    else
        hl.dispatch(hl.dsp.window.move({ workspace = "special:magic" }))
        local mon = hl.get_active_monitor()
        if mon then
            if not win.floating then scratchpadFloated[win.address] = true end
            -- Monitor width/height are pre-transform; swap for portrait.
            local w, h = mon.width / mon.scale, mon.height / mon.scale
            if mon.transform % 2 == 1 then w, h = h, w end
            hl.dispatch(hl.dsp.window.float({ action = "enable" }))
            hl.dispatch(hl.dsp.window.resize({ x = math.floor(w * 0.65), y = math.floor(h * 0.65), exact = true }))
            hl.dispatch(hl.dsp.window.center())
        end
    end
end, { description = "Workspaces | Move to/from scratchpad" })

-- Waybar's scratchpad badge is signal-driven (interval "once" + RTMIN+9 in
-- modules/home/wm/waybar.nix) — poke it on the events that can change the
-- special-workspace window count. Toggling a special's visibility doesn't
-- change the count, so it needs no poke.
local function pokeScratchpadBadge()
    hl.exec_cmd("pkill -RTMIN+9 waybar")
end
for _, ev in ipairs({ "window.open", "window.close", "window.move_to_workspace" }) do
    hl.on(ev, pokeScratchpadBadge)
end

-- Recording indicator (RTMIN+10): screenshare.state fires on both edges of
-- any compositor-visible capture (wlr-screencopy, portal shares — verified
-- with grim). KMS-mode gpu-screen-recorder grabs DRM planes behind the
-- compositor and fires nothing; the module keeps a slow fallback poll whose
-- pgrep branch catches that case.
hl.on("screenshare.state", function()
    hl.exec_cmd("pkill -RTMIN+10 waybar")
end)

-- Per-app scratchpads — run-or-raise: first press spawns the app into its
-- own special workspace (so the scratchpad-style rule applies at open);
-- afterwards the same key just toggles that special. The query is scoped to
-- the special so a window dragged out to a normal workspace is left alone
-- and a fresh instance spawns.
local scratchpads = {
    { key = "grave",         name = "term", class = "dropterm",  cmd = "kitty --class dropterm",          label = "Terminal" },
    { key = "SHIFT + grave", name = "btop", class = "btop-drop", cmd = "kitty --class btop-drop -e btop", label = "btop" },
}
for _, pad in ipairs(scratchpads) do
    scratchpadRule(pad.name)
    hl.bind(mainMod .. " + " .. pad.key, function()
        if #hl.get_windows({ class = pad.class, workspace = "special:" .. pad.name }) == 0 then
            hl.dispatch(hl.dsp.exec_cmd("[workspace special:" .. pad.name .. "] " .. pad.cmd))
        else
            hl.dispatch(hl.dsp.workspace.toggle_special(pad.name))
        end
    end, { description = "Workspaces | Scratchpad: " .. pad.label })
end

-- System
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("hyprlock"),                                                          { description = "System | Lock" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("systemctl suspend"),                                                 { description = "System | Suspend" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle power"),                  { description = "System | Power menu" })
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle notifications"),         { description = "System | Notifications" })
hl.bind(mainMod .. " + Tab",       hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle overview"),              { description = "System | Workspace overview" })
hl.bind(mainMod .. " + I",         hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle settings"),         { description = "System | Settings" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle clipboard"),        { description = "System | Clipboard history" })
hl.bind(mainMod .. " + O",         hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/audio-output.sh"),                       { description = "System | Audio output switcher" })
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/color-picker.sh"),                       { description = "System | Colour picker" })
hl.bind(mainMod .. " + Period",    hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/emoji-picker.sh"),                       { description = "System | Emoji picker" })

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle screenshot"), { description = "Screenshots | Open picker" })

-- Volume (wpctl applies the change; the Quickshell OSD reacts passively to it)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0"), { locked = true, description = "Media | Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),         { locked = true, description = "Media | Volume down" })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),         { locked = true, description = "Media | Mute" })

-- Brightness (apply, then trigger the Quickshell OSD)
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set +10% && ~/.config/hypr/scripts/qs_manager.sh osd brightness"), { locked = true, description = "Media | Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%- && ~/.config/hypr/scripts/qs_manager.sh osd brightness"), { locked = true, description = "Media | Brightness down" })

-- Media
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = "Media | Play/pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),        { locked = true, description = "Media | Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),    { locked = true, description = "Media | Prev track" })

-- Gaming toggle
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/gaming-toggle.sh"), { description = "Gaming | Toggle gaming mode" })

-- Mouse binds
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
