-- ~/.config/hypr/hyprland.lua
-- Hyprland configuration — Gruvbox Material Dark
-- Generated from hyprlang settings block; verify dispatcher names against
-- /usr/share/hypr/stubs/ if anything behaves unexpectedly.

-- Monitor/workspace config is per-host; generated by Nix into monitors.lua
require("monitors")

--------------------
---- ENVIRONMENT ---
--------------------

hl.env("XCURSOR_SIZE",               "24")
hl.env("XCURSOR_THEME",              "Bibata-Modern-Classic")
hl.env("GTK_THEME",                  "Gruvbox-Material-Dark")
hl.env("__GLX_VENDOR_LIBRARY_NAME",  "nvidia")
hl.env("LIBVA_DRIVER_NAME",          "nvidia")
hl.env("__GL_GSYNC_ALLOWED",         "1")
hl.env("__GL_VRR_ALLOWED",           "1")

--------------------
---- AUTOSTART -----
--------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland DISPLAY")
    hl.exec_cmd("GSK_RENDERER=gl swayosd-server")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("swww img ~/.config/hyprland/wallpaper.jpg --transition-type wipe --transition-fps 60")
    hl.exec_cmd("swaync")
    hl.exec_cmd("playerctld")
    hl.exec_cmd("/run/current-system/sw/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("sleep 1 && nm-applet --indicator")
    hl.exec_cmd("sleep 1.5 && syncthingtray")
    hl.exec_cmd("gammastep")
end)

--------------------
---- SETTINGS ------
--------------------

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },

    input = {
        kb_layout        = "us",
        follow_mouse     = 1,
        sensitivity      = 0,
        accel_profile    = "flat",
        touchpad = {
            natural_scroll       = true,
            disable_while_typing = true,
            tap_to_click         = true,
        },
    },

    general = {
        gaps_in         = 5,
        gaps_out        = 10,
        border_size     = 2,
        layout          = "dwindle",
        allow_tearing   = true,
        col = {
            active_border   = { colors = { "rgba(7daea3ee)", "rgba(d3869bee)" }, angle = 45 },
            inactive_border = "rgba(3c3836aa)",
        },
    },

    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size    = 3,
            passes  = 1,
        },
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    gestures = {
        workspace_swipe_distance = 300,
    },

    misc = {
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
        vrr                      = 2,
    },
})

-- Animations
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",    enabled = true, speed = 7,  bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7,  bezier = "default",   style = "popin 80%" })
hl.animation({ leaf = "border",     enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle",enabled = true, speed = 8,  bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = 7,  bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6,  bezier = "default" })

---------------------
---- LAYER RULES ----
---------------------

hl.layer_rule({ match = { namespace = "waybar" },                 blur = true,  ignore_alpha = 0.0 })
hl.layer_rule({ match = { namespace = "swaync-control-center" },  blur = true,  ignore_alpha = 0.0 })
hl.layer_rule({ match = { namespace = "notifications" },          blur = true,  ignore_alpha = 0.0 })

---------------------
---- WINDOW RULES ---
---------------------

-- Gaming — allow tearing
hl.window_rule({ match = { class = "steam_app_" },                  immediate = true })
hl.window_rule({ match = { class = "Minecraft" },                   immediate = true })

-- Launchers
hl.window_rule({ match = { class = "steam",   title = "Steam Big Picture Mode" }, fullscreen = true })
hl.window_rule({ match = { class = "lutris" }, workspace = "10 silent" })
hl.window_rule({ match = { class = "steam"  }, workspace = "10 silent" })

-- Float
hl.window_rule({ match = { class = "pavucontrol" },        float = true })
hl.window_rule({ match = { class = "nm-connection-editor" }, float = true })
hl.window_rule({ match = { class = "blueman-manager" },    float = true })
hl.window_rule({ match = { title = "Picture-in-Picture" }, float = true })

-- Opacity
hl.window_rule({ match = { class = "kitty" },        opacity = "0.90 override 0.90 override" })
hl.window_rule({ match = { class = "firefox" },      opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "chromium" },     opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "google-chrome" },opacity = "1.0 override 1.0 override" })

-- Workspace assignments
hl.window_rule({ match = { class = "firefox" }, workspace = "1" })
hl.window_rule({ match = { class = "Code"    }, workspace = "2" })
hl.window_rule({ match = { class = "kitty"   }, workspace = "3" })
hl.window_rule({ match = { class = "discord" }, workspace = "4" })

--------------------
---- KEYBINDS ------
--------------------

local mainMod = "SUPER"

-- Apps
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + E",      hl.dsp.exec_cmd("nautilus"))
hl.bind(mainMod .. " + B",      hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + D",      hl.dsp.exec_cmd("fuzzel"))
hl.bind(mainMod .. " SHIFT + D",hl.dsp.exec_cmd("fuzzel --terminal=kitty"))

-- Window management
hl.bind(mainMod .. " + Q",       hl.dsp.window.kill())
hl.bind(mainMod .. " SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + F",       hl.dsp.window.fullscreen())
hl.bind(mainMod .. " SHIFT + F", hl.dsp.window.fullscreen({ client_state = 0, internal_state = 3 }))
hl.bind(mainMod .. " + Space",   hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P",       hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J",       hl.dsp.layout("togglesplit"))

-- Focus
hl.bind(mainMod .. " + left",  hl.dsp.window.focus("l"))
hl.bind(mainMod .. " + right", hl.dsp.window.focus("r"))
hl.bind(mainMod .. " + up",    hl.dsp.window.focus("u"))
hl.bind(mainMod .. " + down",  hl.dsp.window.focus("d"))

-- Move window
hl.bind(mainMod .. " SHIFT + left",  hl.dsp.window.move("l"))
hl.bind(mainMod .. " SHIFT + right", hl.dsp.window.move("r"))
hl.bind(mainMod .. " SHIFT + up",    hl.dsp.window.move("u"))
hl.bind(mainMod .. " SHIFT + down",  hl.dsp.window.move("d"))

-- Resize window
hl.bind(mainMod .. " CTRL + left",  hl.dsp.window.resize({ x = -50, y = 0 }))
hl.bind(mainMod .. " CTRL + right", hl.dsp.window.resize({ x = 50,  y = 0 }))
hl.bind(mainMod .. " CTRL + up",    hl.dsp.window.resize({ x = 0,   y = -50 }))
hl.bind(mainMod .. " CTRL + down",  hl.dsp.window.resize({ x = 0,   y = 50 }))

-- Workspaces 1–10
for i = 1, 10 do
    local key = tostring(i % 10)  -- 10 maps to "0"
    hl.bind(mainMod .. " + " .. key,         hl.dsp.workspace.switch(i))
    hl.bind(mainMod .. " SHIFT + " .. key,   hl.dsp.window.move_to_workspace(i))
end

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.workspace.switch("e+1"))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.workspace.switch("e-1"))

-- Scratchpad
hl.bind(mainMod .. " + S",         hl.dsp.workspace.special("magic"))
hl.bind(mainMod .. " SHIFT + S",   hl.dsp.window.move_to_workspace("special:magic"))

-- System
hl.bind(mainMod .. " + L",         hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " SHIFT + L",   hl.dsp.exec_cmd("systemctl suspend"))
hl.bind(mainMod .. " SHIFT + E",   hl.dsp.exec_cmd("wlogout -p layer-shell"))
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(mainMod .. " SHIFT + V",   hl.dsp.exec_cmd("cliphist list | fuzzel -d | cliphist decode | wl-copy"))

-- Screenshots
hl.bind("Print",             hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))
hl.bind("SHIFT + Print",     hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd('grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).png'))

-- Volume
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })

-- Brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set +10%"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"), { locked = true })

-- Media
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),        { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),    { locked = true })

-- Gaming toggle
hl.bind(mainMod .. " SHIFT + G", hl.dsp.exec_cmd("~/.config/hypr/scripts/gaming-toggle.sh"))

-- Mouse binds
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
