# hosts/work-laptop/hardware-configuration.nix
# Generated by nixos-generate-config on the target machine.
#
# Machine: Lenovo ThinkBook 14 2-in-1 G4 IML (DMI model 21MX).
#   CPU  Intel Core Ultra 7 155U (Meteor Lake) — 12 cores / 14 threads
#        (2 P + 8 E + 2 LP-E), hence the kvm-intel module and the NPU below.
#   iGPU Intel Graphics (Xe-LPG, 4 cores). No discrete GPU — this host imports
#        neither nvidia.nix nor cuda.nix.
#   RAM  16 GB soldered (15.3 GiB usable). Not upgradeable, which is what makes
#        the swapfile below load-bearing rather than a nicety.
#   Disk NixOS lives on an external ADATA ELITE SE880 (USB, 476 GB) — see
#        disk-config.nix. The internal SK hynix HFS512GEJ4X112N (NVMe, 512 GB)
#        is untouched and holds Windows, which Limine chainloads by the ESP
#        partition GUID pinned in default.nix.
#
# NOTE: fileSystems are NOT defined here — disko (disk-config.nix) manages them.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "uas"
        "usbhid"
        "sd_mod"
        "sdhci_pci"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  # 16G swapfile — matches the ThinkBook's 16G of RAM.
  #
  # base.nix enables zramSwap for every host, but zram is *compressed RAM*: it
  # stretches what fits in memory and adds no capacity beyond it, so a working
  # set that genuinely exceeds RAM still reached the OOM killer. This gives the
  # overflow somewhere real to land.
  #
  # zramSwap defaults to priority 5 and an unprioritised swapfile lands below
  # that, so the kernel fills zram first and only spills to the USB SSD after —
  # which is what we want, the bus being far slower than RAM. Left unset rather
  # than pinned so that ordering keeps following zramSwap's own default.
  #
  # Lives on the root subvolume rather than a dedicated @swap one: adding a
  # subvolume to disk-config.nix only takes effect at disko install time, so on
  # this already-installed drive the generated mount would fail at boot. On
  # btrfs, NixOS creates this with `btrfs filesystem mkswapfile`, which sets
  # nodatacow/nodatasum on the file — the root mount's compress=zstd therefore
  # does not apply to it, and no manual chattr is needed. Created automatically
  # on the first rebuild; nothing to prepare by hand.
  #
  # No hibernation: that additionally needs boot.resumeDevice plus a resume
  # offset, and hibernating onto a removable drive is not worth the fragility.
  # Note the same fragility applies to swap itself here — if the USB link resets
  # mid-session the swapped-out pages go with it, which the kernel does not
  # survive gracefully. Still strictly better than the OOM kills it replaces.
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024; # MiB
    }
  ];

  hardware.cpu.intel = {
    npu.enable = true;
    updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
