# hosts/home-desktop/hardware-configuration.nix
# Generated by nixos-generate-config on the target machine.
# NOTE: fileSystems are NOT defined here — disko (disk-config.nix) manages them.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "uas"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ]; # NVIDIA modules added by modules/nixos/nvidia.nix

  # Intel i7-13700K
  boot.kernelModules = [
    "kvm-intel"
    "it87"
  ];
  boot.extraModprobeConfig = ''
    options it87 ignore_resource_conflict=1 force_id=0x8628
  '';
  boot.extraModulePackages = [ ]; # nvidia_x11 added by modules/nixos/nvidia.nix

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
