# hosts/home-desktop/hardware-configuration.nix
# Generated by nixos-generate-config on the target machine.
# NOTE: fileSystems are NOT defined here — disko (disk-config.nix) manages them.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "uas"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ]; # NVIDIA modules added by hosts/common/optional/nvidia.nix
    };
    # Intel i7-13700K
    kernelModules = [
      "kvm-intel"
      "it87"
    ];
    extraModprobeConfig = ''
      options it87 ignore_resource_conflict=1 force_id=0x8628
    '';
    extraModulePackages = [ ]; # nvidia_x11 added by hosts/common/optional/nvidia.nix
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
