---
# =============================================================================
# AUR Role — Variables
# =============================================================================

aur_helper_url: "https://aur.archlinux.org/{{ aur_helper }}.git"
