# modules/home/wm/hyprland.nix — Hyprland window manager configuration.
{
  lib,
  config,
  osConfig,
  pkgs,
  ...
}:
let
  cfg = config.custom.hm;
  renderTheme = import ../../../config/stylix/palette-subst.nix { inherit lib; };

  # Hold the resume path until the GPU is back, then wake the outputs.
  #
  # logind emits PrepareForSleep(false) as soon as systemd-suspend.service
  # finishes, and nvidia-resume.service — which restores the preserved VRAM
  # allocations — is only ordered After= that same unit, so it has not even
  # started when hypridle acts on the signal. Waking and re-rendering inside
  # that window can wedge a hyprlock that survived the suspend: its resource
  # gatherer stops completing, it commits no further frames, and
  # ext-session-lock then obliges the compositor to paint black. Screens lit,
  # nothing on them, no crash to show for it, and after_sleep_cmd's pidof guard
  # keeps the wedged instance rather than replacing it (seen 2026-09-03 16:25;
  # the identical resume 70 minutes earlier was fine, hence a race).
  #
  # Two phases, because the job is still queued when the signal lands: up to 1 s
  # for it to reach "activating", then up to 10 s for it to leave. Both are
  # capped so a stuck unit can never strand the session on a black screen.
  #
  # `systemctl is-active` cannot express this — a Type=oneshot unit stays
  # "activating" for the whole of its ExecStart and never becomes "active", so
  # is-active returns non-zero throughout and the wait would be a no-op.
  # LoadState gates the whole thing at runtime instead of in Nix, so the
  # non-NVIDIA hosts skip it in one systemctl call and nothing here has to
  # duplicate the conditions under which NixOS emits the unit.
  waitForNvidiaResume =
    let
      state = "\"$(systemctl show -p ActiveState --value nvidia-resume.service)\"";
    in
    "if [ \"$(systemctl show -p LoadState --value nvidia-resume.service)\" = loaded ]; then "
    + "i=0; while [ $i -lt 10 ] && [ ${state} != activating ]; do i=$((i+1)); sleep 0.1; done; "
    + "i=0; while [ $i -lt 100 ] && [ ${state} = activating ]; do i=$((i+1)); sleep 0.1; done; "
    + "fi; ";

  # Parse a hyprlang monitor string "NAME,WxH@Hz,XxY,SCALE[,transform,N]"
  # into a Lua hl.monitor({}) call.
  monitorToLua =
    s:
    let
      parts = builtins.map lib.strings.trim (lib.splitString "," s);
      output = builtins.elemAt parts 0;
      mode = builtins.elemAt parts 1;
      position = builtins.elemAt parts 2;
      scale = builtins.elemAt parts 3;
      hasTransform = builtins.length parts >= 6;
      transformVal = if hasTransform then builtins.elemAt parts 5 else "";
    in
    ''hl.monitor({ output = "${output}", mode = "${mode}", position = "${position}", scale = ${scale}${lib.optionalString hasTransform ", transform = ${transformVal}"} })'';

  # Workspaces are intentionally NOT pinned to monitors: with no
  # hl.workspace_rule() monitor binds, all 1–9 are a shared dynamic pool,
  # freely movable between monitors. The *initial* placement (ws1→primary,
  # ws2→secondary) is instead set once at startup in
  # config/hypr/hyprland.lua's autostart, using the connector names exported
  # by monitors.lua below.
  secName =
    if cfg.monitors.secondary != null then
      lib.head (lib.splitString "," cfg.monitors.secondary)
    else
      "";

  # The generated monitors.lua content
  monitorsLua = ''
    -- Auto-generated by Nix from modules/home/wm/hyprland.nix
    -- Do not edit manually.

    ${lib.optionalString (cfg.monitors.secondary != null) (monitorToLua cfg.monitors.secondary)}
    ${lib.optionalString (cfg.monitors.primary != null) (monitorToLua cfg.monitors.primary)}
    ${lib.optionalString (
      cfg.monitors.primary == null
    ) ''hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })''}

    -- Runtime layout saved from the Quickshell Monitors page — written by
    -- config/hypr-scripts/monitor-layout.sh, not managed by Nix. Applied last
    -- so it wins over the declarations above. loadfile returns nil when the
    -- file is absent (the usual case), and pcall keeps a half-written or
    -- hand-mangled file from taking the whole config down.
    local savedLayout = loadfile("${config.home.homeDirectory}/.config/hypr/monitors-local.lua")
    if savedLayout then pcall(savedLayout) end

    -- Consumed by hyprland.lua: cursor.default_monitor (spawn cursor on
    -- primary) and the startup workspace placement (primary/secondary).
    -- Absent monitors export "" so callers can skip them.
    return {
      primary = "${cfg.monitors.primaryName}",
      secondary = "${secName}",
    }
  '';

  # The cheat sheet is one shared document; only the subtitle is per-host.
  shortcutsMd = builtins.replaceStrings [ "@host@" ] [ osConfig.networking.hostName ] (
    builtins.readFile ../../../docs/SHORTCUTS.md
  );

  # The generated env.lua content — per-host env vars plus app choices.
  # Returns a table that hyprland.lua's keybinds consume via require("env").
  envLua = ''
    -- Auto-generated by Nix from modules/home/wm/hyprland.nix
    -- Do not edit manually.
    hl.env("TERMINAL", "${cfg.terminal}")
    hl.env("BROWSER",  "${cfg.browser}")
    ${lib.optionalString cfg.nvidia ''
      hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
      hl.env("LIBVA_DRIVER_NAME",         "nvidia")
      hl.env("__GL_GSYNC_ALLOWED",        "1")
      hl.env("__GL_VRR_ALLOWED",          "1")''}

    return {
      terminal = "${cfg.terminal}",
      browser  = "${cfg.browser}",
    }
  '';

  # The generated wallpaper.lua content — per-output awww invocations.
  # All outputs crop-fill the leaves wallpaper; a rotated/portrait secondary is
  # then overridden with a rendered SHORTCUTS.md cheat-sheet
  # (see config/hypr-scripts/shortcuts-wallpaper.sh).
  wallpaperLua =
    let
      transition = "--transition-type wipe --transition-fps 60";
      secName = lib.optionalString (cfg.monitors.secondary != null) (
        lib.head (lib.splitString "," cfg.monitors.secondary)
      );
      secRotated =
        cfg.monitors.secondary != null && builtins.length (lib.splitString "," cfg.monitors.secondary) >= 6;
    in
    ''
      -- Auto-generated by Nix from modules/home/wm/hyprland.nix
      -- Do not edit manually.
      hl.exec_cmd("awww img ~/.config/hypr/wallpaper.png --resize crop ${transition}")
    ''
    + lib.optionalString secRotated ''
      hl.exec_cmd("bash ~/.config/hypr/scripts/shortcuts-wallpaper.sh ${secName}")
    '';
in
{
  options.custom.hm = {
    compositor = lib.mkOption {
      type = lib.types.enum [
        "hyprland"
        "none"
      ];
      default = "none";
      description = "Which Wayland compositor to configure for this user.";
    };

    nvidia = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to set NVIDIA-specific Hyprland environment variables.";
    };

    terminal = lib.mkOption {
      type = lib.types.str;
      default = "kitty";
      description = "Terminal command — used by the Super+Return bind and exported as $TERMINAL.";
    };

    browser = lib.mkOption {
      type = lib.types.str;
      default = "zen-beta";
      description = "Browser command — used by the Super+B bind and exported as $BROWSER.";
    };

    monitors = {
      primary = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Primary monitor string, e.g. DP-3,2560x1440@165,2160x0,1";
      };
      primaryName = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Connector name of the primary monitor, e.g. DP-3. Used to pin workspaces.";
      };
      secondary = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Secondary monitor string, e.g. DP-2,3840x2160@60,0x0,1,transform,3";
      };
    };
  };

  config = lib.mkIf (cfg.compositor == "hyprland") {

    xdg.configFile = {
      # ── Store-symlinked scripts (gaming-toggle, screenshot, lock, …) ────────
      # Theme.qml is a template: its @token@ palette placeholders are rendered
      # from config/stylix/palette.nix; everything else is copied verbatim.
      "hypr/scripts".source = pkgs.runCommand "hypr-scripts" { } ''
        cp -r ${../../../config/hypr-scripts} $out
        chmod -R u+w $out
        cp ${pkgs.writeText "Theme.qml" (renderTheme ../../../config/hypr-scripts/quickshell/Theme.qml)} \
          $out/quickshell/Theme.qml
      '';
      # ── Per-host monitor + workspace config (generated by Nix) ──────────────
      "hypr/monitors.lua".text = monitorsLua;
      # ── Per-host environment variables (generated by Nix) ────────────────────
      "hypr/env.lua".text = envLua;
      # ── Per-host wallpaper command(s) (generated by Nix) ─────────────────────
      "hypr/wallpaper.lua".text = wallpaperLua;
      # ── Wallpaper — deployed to ~/.config/hypr/wallpaper.png, set by awww ─────
      "hypr/wallpaper.png".source = ../../../config/sddm/leaves-wall.png;
      # ── Shortcuts cheat-sheet source + style (rendered onto the 2nd monitor) ─
      # @host@ is substituted so the subtitle names the machine the sheet is
      # actually deployed on, rather than whichever host it was written for.
      "hypr/shortcuts.md".text = shortcutsMd;
      "hypr/shortcuts.css".text = renderTheme ../../../config/hypr/shortcuts.css;
    };

    # ── Tray applets — systemd user services instead of sleep-raced exec-once ─
    # Both HM services bind to tray.target (declared by HM's wayland module).
    # nm-applet (SNI mode) re-registers once the quickshell tray appears;
    # syncthingtray's default command already passes --wait.
    xsession.preferStatusNotifierItems = true; # nm-applet --indicator (SNI)

    # Polkit authentication agent — GUI privilege prompts (gparted, virt-manager,
    # flatpak system installs). polkit_gnome's binary lives in libexec (never on
    # PATH), so it must be referenced by store path; nothing else in the session
    # provides an agent — without one, auth prompts silently never appear.
    systemd.user.services.polkit-gnome-agent = {
      Unit = {
        Description = "polkit-gnome authentication agent";
        After = [ "graphical-session.target" ];
        PartOf = [ "graphical-session.target" ];
      };
      Service = {
        ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
        Restart = "on-failure";
        RestartSec = 2;
      };
      Install.WantedBy = [ "graphical-session.target" ];
    };

    services = {
      network-manager-applet.enable = true;
      syncthing.tray.enable = true;

      # ── Hypridle ────────────────────────────────────────────────────────────
      hypridle = {
        enable = true;
        settings = {
          general = {
            # pidof guard: don't spawn a second hyprlock if one is already up
            # (lock at 5min then loginctl lock-session at suspend = duplicate = crash).
            lock_cmd = "pidof hyprlock || hyprlock";
            before_sleep_cmd = "loginctl lock-session";
            # pidof guard here too: killing the live hyprlock on resume made
            # Hyprland flash its red "lockscreen died" fallback screen every wake.
            # dpms.sh, not `hyprctl dispatch dpms on` — dispatch args are Lua, so
            # the bare `on` is a parse error and the screens stay black.
            #
            # waitForNvidiaResume is the ordering fix — see the comment on it.
            after_sleep_cmd =
              waitForNvidiaResume + "bash ~/.config/hypr/scripts/dpms.sh on; pidof hyprlock || hyprlock";
          };
          listener = [
            {
              timeout = 300;
              on-timeout = "loginctl lock-session";
            }
            # Blank the screens shortly after the lock rather than leaving them
            # lit until the 15-minute suspend. 30s of grace after hyprlock
            # appears, so the screen doesn't die out from under you mid-password.
            #
            # `idle-off`, not `off`: it no-ops while gaming mode owns the DPMS
            # state, and it leaves wake-on-input armed so a keypress lights them
            # back up. on-resume is the belt-and-braces path for the case where
            # something (a manual blank, gaming mode's exit) left that disarmed.
            {
              timeout = 330;
              on-timeout = "bash ~/.config/hypr/scripts/dpms.sh idle-off";
              on-resume = "bash ~/.config/hypr/scripts/dpms.sh idle-on";
            }
            {
              timeout = 900;
              on-timeout = "systemctl suspend";
            }
          ];
        };
      };
    };

    # ── Hyprland WM — configType "lua" makes HM write hyprland.lua; extraConfig
    # is appended to it. nixpkgs' hyprland is used (the default), which avoids
    # the flake source-tarball evaluation-time fetch issue.
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      configType = "lua";
      extraConfig = renderTheme ../../../config/hypr/hyprland.lua;
      systemd.enable = false; # UWSM handles session/systemd integration
    };
  };
}
