# modules/home/wm/hyprland.nix — Hyprland window manager configuration.
{
  lib,
  config,
  ...
}:
let
  cfg = config.custom.hm;

  # Parse a hyprlang monitor string "NAME,WxH@Hz,XxY,SCALE[,transform,N]"
  # into a Lua hl.monitor({}) call.
  monitorToLua =
    s:
    let
      parts = builtins.map lib.strings.trim (lib.splitString "," s);
      output = builtins.elemAt parts 0;
      mode = builtins.elemAt parts 1;
      position = builtins.elemAt parts 2;
      scale = builtins.elemAt parts 3;
      hasTransform = builtins.length parts >= 6;
      transformVal = if hasTransform then builtins.elemAt parts 5 else "";
    in
    ''hl.monitor({ output = "${output}", mode = "${mode}", position = "${position}", scale = ${scale}${lib.optionalString hasTransform ", transform = ${transformVal}"} })'';

  # Generate hl.workspace_rule() lines for pinning workspaces to monitors
  workspaceRules =
    (lib.optionals (cfg.monitors.primaryName != "") [
      ''hl.workspace_rule({ workspace = "1", monitor = "${cfg.monitors.primaryName}", default = true })''
      ''hl.workspace_rule({ workspace = "2", monitor = "${cfg.monitors.primaryName}" })''
      ''hl.workspace_rule({ workspace = "3", monitor = "${cfg.monitors.primaryName}" })''
    ])
    ++ (lib.optionals (cfg.monitors.secondary != null) (
      let
        secName = lib.head (lib.splitString "," cfg.monitors.secondary);
      in
      [
        ''hl.workspace_rule({ workspace = "4", monitor = "${secName}", default = true })''
        ''hl.workspace_rule({ workspace = "5", monitor = "${secName}" })''
        ''hl.workspace_rule({ workspace = "6", monitor = "${secName}" })''
      ]
    ));

  # The generated monitors.lua content
  monitorsLua = ''
    -- Auto-generated by Nix from modules/home/wm/hyprland.nix
    -- Do not edit manually.

    ${lib.optionalString (cfg.monitors.secondary != null) (monitorToLua cfg.monitors.secondary)}
    ${lib.optionalString (cfg.monitors.primary != null) (monitorToLua cfg.monitors.primary)}
    ${lib.optionalString (
      cfg.monitors.primary == null
    ) ''hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })''}

    ${lib.concatStringsSep "\n" workspaceRules}
  '';

  # The generated env.lua content — NVIDIA vars only on hosts that have the GPU
  envLua = ''
    -- Auto-generated by Nix from modules/home/wm/hyprland.nix
    -- Do not edit manually.
    ${lib.optionalString cfg.nvidia ''
      hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
      hl.env("LIBVA_DRIVER_NAME",         "nvidia")
      hl.env("__GL_GSYNC_ALLOWED",        "1")
      hl.env("__GL_VRR_ALLOWED",          "1")''}
  '';
in
{
  options.custom.hm = {
    compositor = lib.mkOption {
      type = lib.types.enum [
        "hyprland"
        "none"
      ];
      default = "none";
      description = "Which Wayland compositor to configure for this user.";
    };

    nvidia = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to set NVIDIA-specific Hyprland environment variables.";
    };

    monitors = {
      primary = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Primary monitor string, e.g. DP-3,2560x1440@165,2160x0,1";
      };
      primaryName = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Connector name of the primary monitor, e.g. DP-3. Used to pin workspaces.";
      };
      secondary = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Secondary monitor string, e.g. DP-2,3840x2160@60,0x0,1,transform,3";
      };
    };
  };

  config = lib.mkIf (cfg.compositor == "hyprland") {

    xdg.configFile = {
      # ── Live-symlinked scripts (gaming-toggle, screenshot, lock, …) ─────────
      "hypr/scripts".source = ../../../config/hypr-scripts;
      # ── Per-host monitor + workspace config (generated by Nix) ──────────────
      "hypr/monitors.lua".text = monitorsLua;
      # ── Per-host environment variables (generated by Nix) ────────────────────
      "hypr/env.lua".text = envLua;
      # ── Wallpaper — solid Gruvbox dark bg, set by awww on startup ────────────
      "hypr/wallpaper.png".source = config.stylix.image;
    };

    # ── Hypridle ──────────────────────────────────────────────────────────────
    services.hypridle = {
      enable = true;
      settings = {
        general = {
          lock_cmd = "hyprlock";
          before_sleep_cmd = "loginctl lock-session";
          after_sleep_cmd = "hyprctl dispatch dpms on; pkill -x hyprlock; hyprlock";
        };
        listener = [
          {
            timeout = 300;
            on-timeout = "loginctl lock-session";
          }
          {
            timeout = 900;
            on-timeout = "systemctl suspend";
          }
        ];
      };
    };

    # ── Hyprland WM — configType "lua" makes HM write hyprland.lua; extraConfig
    # is appended to it. nixpkgs' hyprland is used (the default), which avoids
    # the flake source-tarball evaluation-time fetch issue.
    wayland.windowManager.hyprland = {
      enable = true;
      xwayland.enable = true;
      configType = "lua";
      extraConfig = builtins.readFile ../../../config/hypr/hyprland.lua;
      systemd.enable = false; # UWSM handles session/systemd integration
    };
  };
}
