# wip/swayosd.nix — SwayOSD volume/brightness overlay, removed from active config 2026-05-14.
# Re-add once ready to wire behind a proper toggle.
#
# ── modules/nixos/productivity.nix ────────────────────────────────────────────
# Add to environment.systemPackages:
#
#   # Volume/brightness OSD
#   swayosd
#
# ── modules/home/apps.nix ─────────────────────────────────────────────────────
# Restore service config (style is generated by matugen into ~/.config/swayosd/style.css):
#
#   services.swayosd = {
#     enable = true;
#     topMargin = 0.9;
#     stylePath = "${config.home.homeDirectory}/.config/swayosd/style.css";
#   };
#
# Restore swayosd style placeholder activation (prevents swayosd failing before matugen runs):
#
#   home.activation.initSwayosdStyle = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
#     if [ ! -f "$HOME/.config/swayosd/style.css" ]; then
#       mkdir -p "$HOME/.config/swayosd"
#       touch "$HOME/.config/swayosd/style.css"
#     fi
#   '';
#
# ── modules/home/wm/hyprland.nix ──────────────────────────────────────────────
# Add to exec-once:
#
#   "swayosd-server"
#
# Add to bind:
#
#   # Volume
#   ", XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise"
#   ", XF86AudioLowerVolume, exec, swayosd-client --output-volume lower"
#   ", XF86AudioMute,        exec, swayosd-client --output-volume mute-toggle"
#   ", XF86AudioMicMute,     exec, swayosd-client --input-volume mute-toggle"
#   # Brightness
#   ", XF86MonBrightnessUp,   exec, swayosd-client --brightness raise"
#   ", XF86MonBrightnessDown, exec, swayosd-client --brightness lower"
#   # Caps lock indicator
#   ", Caps_Lock, exec, sleep 0.1 && swayosd-client --caps-lock"
