# modules/nixos/base.nix — Core system packages, networking, fonts, and services.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.custom.base;
in
{
  options.custom.base = {
    enable = lib.mkEnableOption "base system configuration";

    username = lib.mkOption {
      type = lib.types.str;
      default = "max";
      description = "Primary non-root username.";
    };

    timezone = lib.mkOption {
      type = lib.types.str;
      default = "Pacific/Auckland";
      description = "System timezone (TZ database name).";
    };

    powerManagement = lib.mkOption {
      type = lib.types.enum [
        "power-profiles-daemon"
        "tlp"
      ];
      default = "power-profiles-daemon";
      description = "Power management daemon to use.";
    };

    firewall = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable the kernel firewall.";
    };

    hashedPassword = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Hashed password for the primary user (generate with mkpasswd -m yescrypt).";
    };

    initialPassword = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Plaintext initial password — change after first login. Use hashedPassword for anything permanent.";
    };

    sshKeys = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "SSH authorized public keys for the primary user.";
    };

    fancontrol = {
      enable = lib.mkEnableOption "fancontrol service";
      config = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Contents of /etc/fancontrol, generated by running sudo pwmconfig.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    # ── Hardware ──────────────────────────────────────────────────────────────────
    hardware = {
      fancontrol = lib.mkIf (cfg.fancontrol.enable && cfg.fancontrol.config != "") {
        enable = true;
        inherit (cfg.fancontrol) config;
      };
      bluetooth = {
        enable = true;
        powerOnBoot = true;
      };
      enableAllFirmware = true;
      enableRedistributableFirmware = true;
    };

    # ── Locale & timezone ──────────────────────────────────────────────────────
    time.timeZone = cfg.timezone;
    i18n.defaultLocale = "en_US.UTF-8";

    # ── Kernel ─────────────────────────────────────────────────────────────────
    # Known risk: home-desktop builds the out-of-tree it87 module (fancontrol)
    # against this kernel — a `latest` bump can break the module until the
    # driver catches up. Accepted; fall back to the default LTS kernel if it bites.
    boot.kernelPackages = pkgs.linuxPackages_latest;
    boot.loader.systemd-boot.configurationLimit = lib.mkDefault 5;

    # ── Networking ─────────────────────────────────────────────────────────────
    networking.networkmanager.enable = true;
    networking.firewall.enable = cfg.firewall;

    # ── Services ──────────────────────────────────────────────────────────────────
    services = {
      blueman.enable = true;
      printing.enable = true;
      timesyncd.enable = lib.mkDefault true;
      power-profiles-daemon.enable = cfg.powerManagement == "power-profiles-daemon";
      # TLP settings live in the host file (see work-laptop); base only enables it.
      tlp.enable = cfg.powerManagement == "tlp";
      gnome.gnome-keyring.enable = true;
      upower.enable = true;

      # Let the Quickshell Battery tab write the laptop charge-limit threshold
      # (e.g. Framework) without root. No-ops on machines lacking the attribute.
      udev.extraRules = ''
        ACTION=="add|change", SUBSYSTEM=="power_supply", KERNEL=="BAT*", RUN+="${pkgs.coreutils}/bin/chmod 0666 /sys/class/power_supply/%k/charge_control_end_threshold"
      '';
    };

    # ── Security / auth ────────────────────────────────────────────────────────
    security.polkit.enable = true;
    security.rtkit.enable = true; # required by PipeWire real-time scheduling

    programs = {
      gnupg.agent = {
        enable = true;
        enableSSHSupport = true;
      };

      # ── Shell ────────────────────────────────────────────────────────────────
      zsh.enable = true;

      # nh clean replaces nix.gc (the two conflict): unlike nix-collect-garbage it
      # also prunes user/HM profile generations and stale result gcroots.
      nh = {
        enable = true;
        flake = "/etc/nixos";
        clean = {
          enable = true;
          dates = "weekly";
          extraArgs = "--keep 5 --keep-since 14d";
        };
      };
    };

    # ── Primary user ───────────────────────────────────────────────────────────
    users.users.${cfg.username} = {
      isNormalUser = true;
      extraGroups = [
        "wheel"
        "networkmanager"
        "audio"
        "video"
        "render"
        "input"
        "lp"
      ]
      ++ lib.optionals config.virtualisation.libvirtd.enable [
        "libvirtd"
        "kvm"
      ]
      ++ lib.optionals config.virtualisation.podman.enable [ "podman" ]
      ++ lib.optionals config.programs.steam.enable [ "gamemode" ];
      shell = pkgs.zsh;
      inherit (cfg) hashedPassword initialPassword;
      openssh.authorizedKeys.keys = cfg.sshKeys;
    };

    # ── System packages ────────────────────────────────────────────────────────
    environment.systemPackages = with pkgs; [
      # Core utilities
      coreutils
      findutils
      gnused
      gnutar
      bc
      curl
      wget
      rsync
      openssh
      gnupg
      man-db
      man-pages
      bash-completion

      # Networking tools
      inetutils
      dnsutils
      traceroute
      nethogs
      iotop
      wireguard-tools
      openvpn
      networkmanagerapplet

      # Filesystem
      dosfstools
      exfatprogs
      btrfs-progs
      p7zip
      unzip
      unrar
      zip
      gparted
      parted

      # Wayland / display
      xdg-utils
      xdg-user-dirs
      wl-clipboard
      qt5.qtwayland
      qt6.qtwayland
      libsForQt5.qt5ct
      kdePackages.qt6ct

      # CLI essentials
      git
      git-lfs
      bat
      eza
      fd
      fzf
      ripgrep
      jq
      zsh
      tmux
      fastfetch
      btop
      delta
      libnotify

      # Monitoring
      lm_sensors

      # upower — needed by Waybar battery module
    ];

    # ── Fonts ──────────────────────────────────────────────────────────────────
    fonts = {
      enableDefaultPackages = true;
      fontDir.enable = true;
      packages = with pkgs; [
        nerd-fonts.jetbrains-mono
        noto-fonts-color-emoji
      ];
    };

    # ── XDG portals (base — compositor modules add their own) ─────────────────
    xdg.portal =
      let
        gtkPortal = pkgs.xdg-desktop-portal-gtk;
      in
      {
        enable = true;
        extraPortals = [ gtkPortal ];
        configPackages = [ gtkPortal ];
      };

    # ── Nix settings ───────────────────────────────────────────────────────────
    nix.settings = {
      experimental-features = [
        "nix-command"
        "flakes"
      ];
      auto-optimise-store = true;
      download-buffer-size = 268435456; # 256 MiB
      # Cap concurrent builds. These hosts have limited RAM and no disk swap;
      # unbounded parallelism (max-jobs = auto) lets several heavy C++ builds
      # run at once and the kernel OOM-killer kills a build → rebuild fails.
      # One job at a time keeps peak memory bounded (cores = 0 still lets that
      # single build use every core). mkDefault so a roomier host can raise it.
      max-jobs = lib.mkDefault 1;
    };

    # Compressed RAM swap. Gives memory pressure somewhere to spill during large
    # rebuilds without a disk partition (works on the portable USB-booted hosts).
    zramSwap.enable = true;
  };
}
