# hosts/framework/default.nix — Framework Laptop 13 Pro (Intel Core Ultra X7 358H,
# Panther Lake, Arc Xe3 iGPU). Personal + work machine: the home-desktop feature
# set minus the things that only make sense on a desktop with a discrete GPU
# (nvidia, cuda, fan2go, the Apollo streaming *host*).
#
# Platform support — kernel params, the Framework EC kmod, framework-tool, fwupd,
# fprintd, acpilight, the headphone-noise and Ethernet-card udev rules — comes
# from nixos-hardware's `framework-intel-core-ultra-series3` module, imported
# from flake.nix alongside disko. Don't restate any of it here.
{ lib, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix
    ./disk-config.nix
    ../../modules/nixos/base.nix
    ../common/optional/development.nix
    ../common/optional/podman.nix
    ../common/optional/libvirt.nix
    ../common/optional/db-gui.nix
    ../common/optional/duckdb.nix
    ../common/optional/cloud-tools.nix
    ../common/optional/productivity.nix
    ../common/optional/creative-apps.nix
    ../common/optional/streaming-tools.nix
    ../common/optional/google-chrome.nix
    ../common/optional/comms.nix
    ../common/optional/stylix.nix
    ../common/optional/gaming.nix
    ../common/optional/wine.nix
    ../common/optional/lan-mouse.nix
    ../common/optional/limine.nix
  ];

  home-manager.backupFileExtension = "backup";

  # ── Base ─────────────────────────────────────────────────────────────────────
  # powerManagement is left at base.nix's default (power-profiles-daemon) rather
  # than work-laptop's TLP: the Quickshell control centre drives profiles through
  # `powerprofilesctl`, which only exists with power-profiles-daemon, and
  # nixos-hardware's laptop module already backs off TLP when ppd is on. Swap to
  # `powerManagement = "tlp";` (and copy work-laptop's settings block) if battery
  # life turns out to need the finer-grained knobs.
  custom.base = {
    enable = true;
    username = "max";
    hashedPassword = "$y$j9T$2U13TXbQqrmp.PD068E0E.$1uJPVe1dF1C0KhlXbn.iMg2qthRxOdp.9s/h6GG6YC6";
    sshKeys = [ ]; # add your public key: "ssh-ed25519 AAAA..."
  };

  # ── Nix builds ───────────────────────────────────────────────────────────────
  # base.nix caps max-jobs at 1 for the RAM-constrained hosts. Once the installed
  # RAM is known and comfortable (home-desktop uses "auto" at 62 GiB), raise it:
  #   nix.settings.max-jobs = "auto";

  # ── Graphics (Arc Xe3 iGPU) ──────────────────────────────────────────────────
  # There is no discrete GPU here, so the iGPU carries video decode, compute and
  # gaming. nixos-hardware's common/gpu/intel supplies the driver packages
  # (intel-media-driver + 32-bit sibling for Proton/Wine, intel-compute-runtime,
  # vpl-gpu-rt) — only its defaults need correcting, so don't add them by hand to
  # hardware.graphics.extraPackages here.
  hardware.intelgpu = {
    # Defaults to i915, which predates Xe3. Panther Lake needs the `xe` DRM
    # driver; the module also loads it in initrd for early KMS.
    driver = "xe";
    # Default (null) installs *both* VA-API drivers. The i965-era
    # intel-vaapi-driver only covers Gen8–11, and pulling it in also drags in
    # intel-ocl, whose source tarball 404s at Intel — an unbuildable closure.
    vaapiDriver = "intel-media-driver";
  };

  environment = {
    # Pin the VA-API driver — libva's autodetection still guesses i965 on some
    # Intel PCI IDs, which silently disables hardware decode.
    sessionVariables.LIBVA_DRIVER_NAME = "iHD";

    systemPackages = with pkgs; [
      # Moonlight client — streams games from home-desktop's Apollo host.
      # gaming-streaming.nix is deliberately NOT imported: it also enables the
      # Apollo *server*, which belongs on the desktop, not here.
      moonlight-qt
      # VA-API sanity check: `vainfo` should report the iHD driver.
      libva-utils
    ];
  };

  # ── Fingerprint reader ───────────────────────────────────────────────────────
  # services.fprintd comes from nixos-hardware. Enrol once per finger with
  # `fprintd-enroll`, then verify with `fprintd-verify`. PAM picks it up
  # automatically everywhere (sudo, SDDM, hyprlock) because each service's
  # `fprintAuth` defaults to services.fprintd.enable.

  # ── Bootloader ───────────────────────────────────────────────────────────────
  # Limine (themed menu + generation cap) comes from ../common/optional/limine.nix.
  # No Windows chainload entry — this disk is Linux-only (see disk-config.nix).
  boot = {
    loader.efi.canTouchEfiVariables = true;

    # Required for the LUKS passphrase prompt: the systemd initrd unlocks
    # /dev/mapper/cryptroot (device entry generated by disko) and hands the
    # prompt to plymouth/console cleanly.
    initrd.systemd.enable = true;

    # Secure Boot: the Framework ships with it enabled and Setup Mode available
    # from BIOS. Once `sbctl create-keys` + `sbctl enroll-keys` have been run,
    # flip this on and rebuild — Limine signs with the same sbctl keys.
    # loader.limine.secureBoot.enable = true;

    # btrfs "first mount" free-space-tree init creates a brief window where the
    # @nix subvolume is mounted but path lookups fail; retry instead of panicking.
    # (Same guard as home-desktop — same filesystem layout.)
    initrd.systemd.services.initrd-find-nixos-closure.serviceConfig = {
      Restart = "on-failure";
      RestartSec = "3";
      StartLimitBurst = 10;
      StartLimitIntervalSec = "60";
    };
  };

  # ── Lid / suspend ────────────────────────────────────────────────────────────
  # No swap partition, so hibernation isn't possible — suspend-to-idle only.
  # Spelled out so a stray `hibernate` action can't leave the machine wedged.
  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";
    HandleLidSwitchExternalPower = "suspend";
    HandleLidSwitchDocked = "ignore";
  };

  # ── Networking ───────────────────────────────────────────────────────────────
  # iwd handles roaming between APs noticeably better than wpa_supplicant, which
  # matters on a machine that moves between home and the office. NetworkManager
  # (base.nix) stays in charge of profiles; iwd is only the wifi backend.
  networking = {
    hostName = "framework";
    networkmanager.wifi.backend = lib.mkDefault "iwd";
    wireless.iwd.enable = true;
  };

  system.stateVersion = "26.05";
}
